### ISSUE TITLE
Does Poyo need a `safe_parse()` method?

### ISSUE THREAD

**Issue by nchammas** [hackebrot/poyo#11]
Or is it [safe by default](http://nedbatchelder.com/blog/201302/war_is_peace.html)?

A brief note on this, perhaps in the README, would be helpful.

**Comment by hackebrot** [comment]
Hi @nchammas! 👋 

Poyo does not support deserialization of arbitrary Python objects, so I would say it is safe.

It can create **dict**, **list**, **str**, **int**, **float**, and **NoneType** values.

Please see the ``parse_`` methods in [parser.py](https://github.com/hackebrot/poyo/blob/master/poyo/parser.py).

**Comment by nchammas** [comment]
Good to hear. If that's part of Poyo's "public contract", so to speak, it would be good to document it officially somewhere.

**Comment by hackebrot** [comment]
Ohh an **bool** obviously.

The example on the README captures really good what Poyo understands.

**Comment by nchammas** [comment]
Okie doke. Fine by me if the README example is how we want to express that Poyo is safe by default, though I think some will find it clearer if it's spelled out for them.

**Comment by hackebrot** [comment]
I'll add a note. 🙇

**Comment by hackebrot** [comment]
Done.

**Comment by nchammas** [comment]
👍 

I only bring this up since most people will come to Poyo from PyYAML, and PyYAML has this design flaw in that it's [not safe by default](http://nedbatchelder.com/blog/201302/war_is_peace.html). So I assume they will be curious to know if Poyo repeats this mistake or not.
