### ISSUE TITLE
The parser fails to parse YAML file starting with "---"

### ISSUE THREAD

**Issue by sathlan** [hackebrot/poyo#3]
Using this simple YAML file:

    ---
    default_context:
      project_name: whazz
      version: 0.0.1
      year: 2016

I get this error

     cookiecutter.exceptions.InvalidConfiguration: Unable to parse YAML file /home/jenkins/workspace/gate-puppet-openstack-cookiecutter-puppet-3-cookiecutter-check/default-config.yaml. Error: None of the known patterns match for ---

According to the specification, a YAML file should start with "---" on
a line of its own: http://www.yaml.org/spec/1.2/spec.html#id2760395

If you change the test file like this :

    diff --git a/tests/foobar.yml b/tests/foobar.yml
    index a0d62ba..3c2cee2 100644
    --- a/tests/foobar.yml
    +++ b/tests/foobar.yml
    @@ -1,3 +1,4 @@
    +---
     default_context: # foobar
         greeting: ?????
         email: "raphael@hackebrot.de"
    
You can easily reproduce it.

**Comment by hackebrot** [comment]
Hi @sathlan, thanks for submitting this issue 🙇 

I might be wrong, but the YAML specs indicate that a **document** needs to start with ``---``. That doesn't necessarily apply to a YAML **file**, right?

**Comment by hackebrot** [comment]
Live on PyPI https://pypi.python.org/pypi/poyo

**Comment by sathlan** [comment]
Great, thanks.
