### ISSUE TITLE
YAML file with comment on the first line of child container cannot be parsed

### ISSUE THREAD

**Issue by jakubka** [hackebrot/poyo#8]
Submitted a PR to demonstrate the bug: #7 

Thanks!

**Comment by hackebrot** [comment]
Thank you @jakubka! 🙇 

I'll have a look, if this is easy to add to the parser.

**Comment by hackebrot** [comment]
Done. Will be in the next release 🙇

**Comment by jakubka** [comment]
Thanks a lot!!
